MODEL:
  TYPE: resnet
  NUM_CLASSES: 1000
  DEPTH: 50
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.01
  LR_POLICY: steps
  STEPS: [0, 35, 55, 80]
  LR_MULT: 0.1
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 0.0003
TRAIN:
  DATASET: IMAGENET
  SPLIT: train
  BATCH_SIZE: 256
  IM_SIZE: 224
  EVAL_PERIOD: 2
TEST:
  DATASET: IMAGENET
  SPLIT: val
  BATCH_SIZE: 200
  IM_SIZE: 224
NUM_GPUS: 4
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
LOG_PERIOD: 50
ACTIVE_LEARNING:
  BUDGET_SIZE: 64058
RESNET:
  NUM_GROUPS: 1
  STRIDE_1X1: false
  TRANS_FUN: bottleneck_transform
  WIDTH_PER_GROUP: 64
