MODEL:
  TYPE: resnet
  DEPTH: 50
  NUM_CLASSES: 1000
RESNET:
  TRANS_FUN: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  STRIDE_1X1: False
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 1e-2
  LR_POLICY: steps
  STEPS: [0, 50, 75]
  LR_MULT: 0.2
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 3e-4
TRAIN:
  DATASET: imagenet
  SPLIT: train
  BATCH_SIZE: 256
  IM_SIZE: 224
  EVAL_PERIOD: 1
TEST:
  DATASET: imagenet
  SPLIT: val
  BATCH_SIZE: 200
  IM_SIZE: 256
  ##For testing uncomment below line
  #WEIGHTS: /raid/shadab/prateek/dgx30/prateek/pycls/al_results/15/checkpoints/valSet_acc_64.9812734082397_model_epoch_0092.pyth
NUM_GPUS: 8
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
ACTIVE_LEARNING:
  ACTIVATE: True
  LSET_PATH: /raid/shadab/prateek/dgx30/prateek/pycls/lSet_IMAGENET.npy
  USET_PATH: /raid/shadab/prateek/dgx30/prateek/pycls/uSet_IMAGENET.npy
  VALSET_PATH: /raid/shadab/prateek/dgx30/prateek/pycls/valSet_IMAGENET.npy
  MODEL_LOAD_DIR: /raid/shadab/prateek/dgx30/prateek/pycls/resnet_8gpu/checkpoints/valSet_acc_61.25936329588015_model_epoch_0198.pyth
  MODEL_SAVE_DIR: /raid/shadab/prateek/dgx30/prateek/pycls/al_results/15/models/Imagenet/
  RESULTS_DIR: /raid/shadab/prateek/dgx30/prateek/pycls/al_results/15/
  BUDGET_SIZE: 64058 #10% of lSet where lSet contains 128k datapoints.
#   MAX_AL_EPOCHS: 3