version: '3'

services:
  reveal:
    image: webpronl/reveal-md
    volumes:
      - ./:/slides
    ports:
      - 1948:1948
    working_dir: /slides
    entrypoint: node /app/bin/reveal-md.js
    command: --preprocessor includes.js --css custom.css slides.md
