MODEL:
  TYPE: vgg
  NUM_CLASSES: 2
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.1
  TYPE: adam
  LR_POLICY: steps
  STEPS: [0]
  LR_MULT: 0.1
  MAX_EPOCH: 5
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 0.0005
TRAIN:
  DATASET: RSNA
  SPLIT: train
  BATCH_SIZE: 256
  IM_SIZE: 32
  EVAL_PERIOD: 1
TEST:
  DATASET: RSNA
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
NUM_GPUS: 1
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
LOG_PERIOD: 40
ACTIVE_LEARNING:
  BUDGET_SIZE: 100
RANDAUG:
  ACTIVATE: False
SWA_MODE:
  ACTIVATE: False