MODEL:
  TYPE: wide_resnet_28_2
  NUM_CLASSES: 100
  DEPTH: 28
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.03
  LR_MULT: 0.2
  LR_POLICY: steps
  STEPS: [0, 60, 120, 160]
  MAX_EPOCH: 5
  MOMENTUM: 0.9
  NESTEROV: True
  WEIGHT_DECAY: 0.0005
TRAIN:
  DATASET: CIFAR100
  SPLIT: train
  BATCH_SIZE: 64
  IM_SIZE: 32
  EVAL_PERIOD: 5
TEST:
  DATASET: CIFAR100
  SPLIT: test
  BATCH_SIZE: 200
  IM_SIZE: 32
NUM_GPUS: 4
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
LOG_PERIOD: 50
ACTIVE_LEARNING:
  BUDGET_SIZE: 5000
