MODEL:
  TYPE: vgg
  DEPTH: 16
  NUM_CLASSES: 1000
VGG:
  NUM_GROUPS: 1
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.05
  LR_POLICY: steps
  STEPS: [0, 30, 60, 90]
  LR_MULT: 0.1
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 0.0003
TRAIN:
  DATASET: IMAGENET
  SPLIT: train
  BATCH_SIZE: 128
  IM_SIZE: 224
  EVAL_PERIOD: 5
TEST:
  DATASET: IMAGENET
  SPLIT: val
  BATCH_SIZE: 60
  IM_SIZE: 256
NUM_GPUS: 4
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: ./vgg_out
PORT: 10002
