MODEL:
  TYPE: resnet
  DEPTH: 50
  NUM_CLASSES: 1000
RESNET:
  TRANS_FUN: bottleneck_transform
  NUM_GROUPS: 1
  WIDTH_PER_GROUP: 64
  STRIDE_1X1: False
BN:
  ZERO_INIT_FINAL_GAMMA: True
OPTIM:
  BASE_LR: 0.1
  LR_POLICY: steps
  STEPS: [0, 140, 160, 180]
  LR_MULT: 0.1
  MAX_EPOCH: 200
  MOMENTUM: 0.9
  NESTEROV: False
  WEIGHT_DECAY: 3e-4
TRAIN:
  DATASET: imagenet
  SPLIT: train
  BATCH_SIZE: 256
  IM_SIZE: 224
  EVAL_PERIOD: 1
TEST:
  DATASET: imagenet
  SPLIT: val
  BATCH_SIZE: 200
  IM_SIZE: 256
  ##For testing uncomment below line
  WEIGHTS: /raid/shadab/prateek/dgx30/prateek/pycls/resnet_8gpu/checkpoints/valSet_acc_61.25936329588015_model_epoch_0198.pyth
NUM_GPUS: 8
DATA_LOADER:
  NUM_WORKERS: 4
CUDNN:
  BENCHMARK: True
OUT_DIR: .
